// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq50tTDaSWlk8uV4sYP4CoPORN0suyHLU',
    appId: '1:590647703031:web:316b2d02e36d35cf76aaf2',
    messagingSenderId: '590647703031',
    projectId: 'commerce-a6f36',
    authDomain: 'commerce-a6f36.firebaseapp.com',
    storageBucket: 'commerce-a6f36.appspot.com',
    measurementId: 'G-B8TEPMYHMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlbH6OHqVMU9P21srJV1vulLlIKhI9Y4',
    appId: '1:590647703031:android:848ac1412d63f18f76aaf2',
    messagingSenderId: '590647703031',
    projectId: 'commerce-a6f36',
    storageBucket: 'commerce-a6f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByHtR96hnjinuPELXrYBdEjFyOpCC9VLU',
    appId: '1:590647703031:ios:ed0ac3a5b9d3656d76aaf2',
    messagingSenderId: '590647703031',
    projectId: 'commerce-a6f36',
    storageBucket: 'commerce-a6f36.appspot.com',
    iosBundleId: 'com.example.ecommFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByHtR96hnjinuPELXrYBdEjFyOpCC9VLU',
    appId: '1:590647703031:ios:ed0ac3a5b9d3656d76aaf2',
    messagingSenderId: '590647703031',
    projectId: 'commerce-a6f36',
    storageBucket: 'commerce-a6f36.appspot.com',
    iosBundleId: 'com.example.ecommFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq50tTDaSWlk8uV4sYP4CoPORN0suyHLU',
    appId: '1:590647703031:web:73e7ab3c6d4e140876aaf2',
    messagingSenderId: '590647703031',
    projectId: 'commerce-a6f36',
    authDomain: 'commerce-a6f36.firebaseapp.com',
    storageBucket: 'commerce-a6f36.appspot.com',
    measurementId: 'G-DS2L08RB7B',
  );
}
